[client]
showErrorDetails = true
showWarnings = true

[logger]
level = "info"

[server]
headless = true
port = 8501
enableXsrfProtection = true

[ui]
hideTopBar = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
